options:
    editor: ${VISUAL:-${EDITOR:-vi}}
    max_lines: 100000
    intercept_enter: yes
    bracketed_paste: no
    suggestion_color_escape_code: []
    output_file: $work_dir/output.txt
    allow_wait_for_prompt: yes
    wait_for_prompt_monitor_interval: 3
    selector: fzf
commands:
    search_history:
        selector: fzf --no-sort

contexts:
    - name: bash
      patterns:
          - '\[root@.*\]#'
          - '\[\S+@.\S+\]\$'
